[package]
name = "FETISH-RS"
version = "0.1.0"
authors = ["bubble-07 <spagrab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray="0.13.1"
ndarray-linalg="0.12.0"
ndarray_einsum_beta="0.5.0"
rustfft="3.0.1"
rand="0.7.3"
